version: "2"
linters:
  # Start from no linters enabled.
  default: none
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gocyclo
    - misspell
