name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    # install and run locally via e.g.:
    # brew install pre-commit shellcheck && pre-commit run -a
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go.mod
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
  golangci:
    # install and run locally via e.g.:
    # brew install golangci-lint && golangci-lint run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-go@v6.5.0
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9.2.1
        with:
          version: v2.12.2
          args: --timeout=3m
